stages:
  - build

variables:
  GIT_STRATEGY: clone
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}

before_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup

after_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup
  - sudo chown -R gitlab-runner .

build-image:
  stage: build
  variables:
    TAG: "0.1"
    FORCE_TAGS: "false"
  when: manual
  script:
    - docker build -f dockerfiles/Dockerfile -t image .
    - docker tag image ${IMAGE_NAME}:$CI_COMMIT_SHORT_SHA
    - docker push ${IMAGE_NAME}:$CI_COMMIT_SHORT_SHA
    - >
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ] || [ "$FORCE_TAGS" == "true" ]; then
        docker tag image ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:latest
        docker pull ${IMAGE_NAME}:${TAG} || docker tag image ${IMAGE_NAME}:${TAG} &&  docker push ${IMAGE_NAME}:${TAG}
      fi
  tags:
    - rse-multi-builder
