import os
from dotenv import load_dotenv

load_dotenv()

TRAME_UCAMS_AUTH_URL = os.getenv("TRAME_UCAMS_AUTH_URL")
TRAME_UCAMS_TOKEN_URL = os.getenv("TRAME_UCAMS_TOKEN_URL")
TRAME_UCAMS_CLIENT_ID = os.getenv("TRAME_UCAMS_CLIENT_ID")
TRAME_UCAMS_CLIENT_SECRET = os.getenv("TRAME_UCAMS_CLIENT_SECRET")
TRAME_UCAMS_REDIRECT_URL = os.getenv("TRAME_UCAMS_REDIRECT_URL")
TRAME_UCAMS_SCOPES = os.getenv("TRAME_UCAMS_SCOPES")

TRAME_XCAMS_AUTH_URL = os.getenv("TRAME_XCAMS_AUTH_URL")
TRAME_XCAMS_TOKEN_URL = os.getenv("TRAME_XCAMS_TOKEN_URL")
TRAME_XCAMS_CLIENT_ID = os.getenv("TRAME_XCAMS_CLIENT_ID")
TRAME_XCAMS_CLIENT_SECRET = os.getenv("TRAME_XCAMS_CLIENT_SECRET")
TRAME_XCAMS_REDIRECT_URL = os.getenv("TRAME_XCAMS_REDIRECT_URL")
TRAME_XCAMS_SCOPES = os.getenv("TRAME_XCAMS_SCOPES")

GALAXY_URL = os.getenv("GALAXY_URL")
GALAXY_API_KEY = os.getenv("GALAXY_API_KEY")
GALAXY_API_KEY_ENDPOINT = os.getenv("GALAXY_API_KEY_ENDPOINT")
GALAXY_HISTORY_ID = os.getenv("GALAXY_HISTORY_ID")
GALAXY_LAUNCHER_HISTORY_NAME = os.getenv("GALAXY_LAUNCHER_HISTORY_NAME")

TRAME_LAUNCHER_TOOL_PATH = os.getenv("TRAME_LAUNCHER_TOOL_PATH", "launcher_app/app/tools.json")

EP_PATH = os.getenv("EP_PATH", "/")
